DROP TABLE YOU_SHALL_NOT_CRASH.ROL_FUNCIONALIDAD
DROP TABLE YOU_SHALL_NOT_CRASH.ROL_USUARIO
DROP TABLE YOU_SHALL_NOT_CRASH.ROL
DROP TABLE YOU_SHALL_NOT_CRASH.FUNCIONALIDAD
DROP TABLE YOU_SHALL_NOT_CRASH.AFILIADO
DROP TABLE YOU_SHALL_NOT_CRASH.USUARIO