DROP FUNCTION YOU_SHALL_NOT_CRASH.SPLIT
DROP TRIGGER YOU_SHALL_NOT_CRASH.NUEVO_AFILIADO
DROP PROCEDURE YOU_SHALL_NOT_CRASH.login
DROP PROCEDURE YOU_SHALL_NOT_CRASH.Insertar_Rol
DROP FUNCTION YOU_SHALL_NOT_CRASH.F_Roles
DROP PROCEDURE YOU_SHALL_NOT_CRASH.Baja_Logica_Rol
DROP PROCEDURE YOU_SHALL_NOT_CRASH.Traer_Info_Afiliado
DROP PROCEDURE YOU_SHALL_NOT_CRASH.Comprar_Bonos
DROP PROCEDURE YOU_SHALL_NOT_CRASH.Registrar_Compra
DROP PROCEDURE YOU_SHALL_NOT_CRASH.Insertar_Agenda 


------------------------------------------------------


DROP TABLE YOU_SHALL_NOT_CRASH.CANCELACION_TURNO
DROP TABLE YOU_SHALL_NOT_CRASH.ESPECIALIDAD_PROFESIONAL
DROP TABLE YOU_SHALL_NOT_CRASH.ITEM_DIAGNOSTICO
DROP TABLE YOU_SHALL_NOT_CRASH.ROL_USUARIO
DROP TABLE YOU_SHALL_NOT_CRASH.ROL_FUNCIONALIDAD
DROP TABLE YOU_SHALL_NOT_CRASH.ROL
DROP TABLE YOU_SHALL_NOT_CRASH.COMPRA_BONO
DROP TABLE YOU_SHALL_NOT_CRASH.ITEM_BONO_FARMACIA
DROP TABLE YOU_SHALL_NOT_CRASH.ITEM_AGENDA
DROP TABLE YOU_SHALL_NOT_CRASH.AGENDA
DROP TABLE YOU_SHALL_NOT_CRASH.ESPECIALIDAD
DROP TABLE YOU_SHALL_NOT_CRASH.TIPO_ESPECIALIDAD
DROP TABLE YOU_SHALL_NOT_CRASH.FUNCIONALIDAD
DROP TABLE YOU_SHALL_NOT_CRASH.SINTOMA
DROP TABLE YOU_SHALL_NOT_CRASH.MEDICAMENTO
DROP TABLE YOU_SHALL_NOT_CRASH.BONO_FARMACIA
DROP TABLE YOU_SHALL_NOT_CRASH.RECETA
DROP TABLE YOU_SHALL_NOT_CRASH.DIAGNOSTICO
DROP TABLE YOU_SHALL_NOT_CRASH.TURNO
DROP TABLE YOU_SHALL_NOT_CRASH.BONO_CONSULTA
DROP TABLE YOU_SHALL_NOT_CRASH.AFILIADO
DROP TABLE YOU_SHALL_NOT_CRASH.PROFESIONAL
DROP TABLE YOU_SHALL_NOT_CRASH.ESTADO_CIVIL
DROP TABLE YOU_SHALL_NOT_CRASH.PLAN_MEDICO
DROP TABLE YOU_SHALL_NOT_CRASH.USUARIO

DROP SCHEMA YOU_SHALL_NOT_CRASH
