CREATE TRIGGER MEJ_POS ON PARTIDO
AFTER UPDATE
AS BEGIN


DECLARE NUEVOS_PARTIDOS CURSOR FOR 
SELECT PART_TORNEO, PART_LOCAL FROM INSERTED WHERE UPDATE(PART_DURACION)
UNION SELECT PART_TORNEO, PART_VISITANTE FROM INSERTED WHERE UPDATE(PART_DURACION)

DECLARE @TORNEO INT
DECLARE @EQUIPO INT

DECLARE @MP_ACTUAL INT

OPEN NUEVOS_PARTIDOS

FETCH NUEVOS_PARTIDOS INTO @TORNEO, @EQUIPO

WHILE @@FETCH_STATUS=0
 BEGIN
 
  SET @MP_ACTUAL = (SELECT TOEQ_MEJOR_POSICION FROM TORNEO_EQUIPO WHERE TOEQ_TORNEO=@TORNEO AND TOEQ_EQUIPO=@EQUIPO )
  
  IF ((@MP_ACTUAL>DBO.POS(@TORNEO, @EQUIPO)) OR @MP_ACTUAL IS NULL )
  UPDATE TORNEO_EQUIPO SET TOEQ_MEJOR_POSICION=DBO.POS(@TORNEO, @EQUIPO)
 
 
  FETCH NUEVOS_PARTIDOS INTO @TORNEO, @EQUIPO
 END
 
CLOSE NUEVOS_PARTIDOS
DEALLOCATE NUEVOS_PARTIDOS
 
END

